name: test-on-pr
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checking out
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: install ubuntu tools
        run: |
          sudo apt-get install python3-dev python3-pip python3-venv python3-wheel gcc libpq-dev -y;
          sudo -H pip3 install --upgrade pip
          sudo -H pip3 install --upgrade setuptools
          sudo -H pip3 install --upgrade wheel
          sudo -H pip3 install --upgrade poetry
      - name: install
        run: make install
      - name: tests
        run: python -m unittest
      - name: run example data_pipeline_simple
        run: |
          cd examples/data_pipeline_simple;
          datajob synthesize --stage stage --config datajob_stack.py;
      - name: run example data_pipeline_with_packaged_project
        run: |
          cd examples/data_pipeline_with_packaged_project;
          datajob synthesize --stage stage --config datajob_stack.py;
