name: test-on-pr
on: pull_request

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checking out
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: install
        run: |
          sudo -H npm install -g aws-cdk
          sudo -H pip3 install --upgrade poetry
          poetry install
          poetry config settings.virtualenvs.create false
      - name: tests
        run: poetry run python -m unittestecho; $?
      - name: run example data_pipeline_simple
        run: |
          cd examples/data_pipeline_simple;
          poetry run datajob synthesize --stage stage --config datajob_stack.py; echo $?
      - name: run example data_pipeline_with_packaged_project
        run: |
          cd examples/data_pipeline_with_packaged_project;
          poetry run datajob synthesize --stage stage --config datajob_stack.py; echo $?
